---
name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - main

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ["nightly"]

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up external applications
        run: |
          # fd is a dependency of telescope
          # https://github.com/sharkdp/fd?tab=readme-ov-file#on-ubuntu
          # make sure it's available as `fd` - there seems to be some conflict in Ubuntu
          sudo apt-get install fd-find
          sudo ln -s $(which fdfind) /usr/local/bin/fd
          fd --version

      - name: Setup Rust toolchain
        run: rustup toolchain install nightly --profile minimal

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.7

      - name: Build rust code with cargo
        run: cargo build --verbose --release

      - name: Test rust code with cargo test
        run: cargo test --all --verbose

      - name: Test lua code with nvim-busted-action
        uses: nvim-neorocks/nvim-busted-action@v1.1.0
        with:
          nvim_version: ${{ matrix.neovim_version }}
          luarocks_version: "3.11.1"

      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install

      - name: Preinstall neovim plugins fo integration-tests
        run: pnpm tui neovim exec "Lazy! sync"
        working-directory: integration-tests

      # need to work around https://github.com/cypress-io/github-action/issues/1246
      - run: pnpm --filter integration-tests exec cypress install

      - name: Run integration-tests with cypress
        uses: cypress-io/github-action@v6
        with:
          install: false
          command: pnpm cy:run

      - uses: actions/upload-artifact@v4.5.0
        if: failure()
        with:
          name: cypress-screenshots
          path: integration-tests/cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
